import { FiltersProvider } from "@/context/filters";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CapsuleProvider } from "@/context/capsules";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CapsuleProvider>
      <FiltersProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </FiltersProvider>
    </CapsuleProvider>
  );
}
